### ISSUE TITLE
need remember trigggerd window

### ISSUE THREAD

**Issue by epheien** [NvChad/menu#10]
1. nvim
2. :split
3. `<C-w>j`
4. :lua require("menu").open('default', { mouse = false, border = false })
5. move to "Lsp Actions" and click <CR> (see image below)
6. q

Expected the cursor to stay in the lower window, but the cursor actually stays in the upper window.

<img width="658" alt="Xnip2024-10-12_17-34-07" src="https://github.com/user-attachments/assets/35a94d00-d5e4-4cf0-b9d1-77c6bfce105c">

**Comment by TheLazyLemur** [comment]
Posted sme issue here

https://github.com/NvChad/menu/issues/8
