### ISSUE TITLE
Feature Request: Add Neo-Tree Menu

### ISSUE THREAD

**Issue by 0xJWLabs** [NvChad/menu#12]
Currently, the project utilizes NvimTree in the menu UI. However, many users, including myself, are using neo-tree. Could you please add neo-tree as an option?

**Comment by siduck** [comment]
i dont use neotree so cant help with that. PR's are welcome. check https://github.com/NvChad/menu/tree/main/lua/menus for examples

**Comment by Mte90** [comment]
I am here for the same reason.
Looking at https://github.com/nvzone/menu/blob/main/lua/menus/nvimtree.lua it isn't clear what to do, just a list of the various actions to return?
Maybe a tiny readme that explain how to customize and add more menus for specific plugins can be helpful.
I don't think to have time but I would like to try.

I suggest to put in the readme the list of the plugin supported like `gitsigns` too.

**Comment by siduck** [comment]
@Mte90  
![image](https://github.com/user-attachments/assets/0c95b7e5-524e-464d-a49c-07985af733c0)


so your table must have list of tables, with name etc and cmd is the command ,it'll execute when you click on the item
