### ISSUE TITLE
NvimTree Menu Not Hide

### ISSUE THREAD

**Issue by pojokcodeid** [NvChad/menu#15]
Hai,

I have a problem, 
if buffer active alpha nvim, NvimTree Menu not hide ..
![image](https://github.com/user-attachments/assets/379f1810-55c3-4ab0-98e5-2fbc4f0b385d)

Neovim Version = 0.10.1
Terminal            = wezterm

Thanks

**Comment by siduck** [comment]
that menu looks empty   :fearful: , closing this as unable to reproduce
