### ISSUE TITLE
Foreground colors not switching along with theme_toggle

### ISSUE THREAD

**Issue by 69keks** [NvChad/menu#2]
Well, as the title suggests, the text colors inside the menu box are not changing when I use the theme toggle switch in the top right corner of the screen.
I have `catppuccin` and `everblush` set in `theme_toggle` option.

This is on the theme catppuccin which is set as default. The menu box is using the colors set in `theme` by default (obviously)..
![2024-10-06-140937_hyprshot](https://github.com/user-attachments/assets/8cd76251-ca8c-4b6c-9dfb-d4d7be428dd6)

and this is when I toggle it to a different theme i.e. everblush using the toggle switch
![image](https://github.com/user-attachments/assets/77a898b7-61ab-407c-a31d-66449787d269)

##### NOTE: I mentioned foreground colors because the bg color is changing properly. It's only the fg when using the toggle switch. Manually setting the theme or restarting after toggling is setting the fg colors properly again.
![image](https://github.com/user-attachments/assets/39c8a059-c53c-455b-a684-15ebb45c8932)

I just installed nvchad, so if it's feasible, please let me know if i'm making an obvious mistake somewhere. I have attached my `chadrc.lua`.
Let me know if you need more info. Thanks!

```lua
---@type ChadrcConfig
local M = {}

M.base46 = {
  theme = "everblush",
  theme_toggle = { "everblush", "catppuccin" },
  hl_override = {
    Comment = { italic = true },
    ["@comment"] = { italic = true },
  },
}

M.ui = {
  telescope = { style = "bordered" },
  statusline = {
    theme = "minimal",
  },
}

M.nvdash = {
  load_on_startup = true,
  header = {
    "",
    "███╗   ███╗███████╗██╗    ██╗   ██╗██╗██╗     ██╗     ██╗",
    "████╗ ████║██╔════╝██║    ██║   ██║██║██║     ██║     ██║",
    "██╔████╔██║█████╗  ██║    ██║   ██║██║██║     ██║     ██║",
    "██║╚██╔╝██║██╔══╝  ██║    ╚██╗ ██╔╝██║██║     ██║     ██║",
    "██║ ╚═╝ ██║███████╗███████╗╚████╔╝ ██║███████╗███████╗██║",
    "╚═╝     ╚═╝╚══════╝╚══════╝ ╚═══╝  ╚═╝╚══════╝╚══════╝╚═╝",
    "",
  },
}

return M
```

**Comment by siduck** [comment]
That is because its a general nvim plugin, not integrated with nvchad's base46

**Comment by 69keks** [comment]
I see. If the integration of menu plugin with base46 is not planned right now, I will just close the issue. It's not exactly a breaking issue or anything.. Thank you for quick reply 🫡
