### ISSUE TITLE
Bug: Error control needed in this scenario

### ISSUE THREAD

**Issue by Zeioth** [NvChad/menu#3]
## Description
Clicking outside of toggleterm while the menu window is open, causes an exception.

## How to repro
* Open toggleterm on float mode with `:ToggleTerm direction=float`
* Right click on it to bring nvmenu
![screenshot_2024-10-06_17-29-55_164598583](https://github.com/user-attachments/assets/5a91006e-9827-4635-b941-dea16dada173)
* Click out of the ToggleTerm window
![screenshot_2024-10-06_17-30-20_980164459](https://github.com/user-attachments/assets/65dd1f81-7b83-4752-ab45-6046d3503918)

**Comment by siduck** [comment]
does this happen with toggleterm only? or other floating windows too

**Comment by siduck** [comment]
ok found the bug

**Comment by siduck** [comment]
toggleterm floating window gets closed when i click outside of it, so menu wasnt able to set cursor!

**Comment by Zeioth** [comment]
I just tested it and this have been fixed indeed!
