### ISSUE TITLE
Feature request: Visual mode support

### ISSUE THREAD

**Issue by Zeioth** [NvChad/menu#4]
## Description
Clicking an element of the menu, currently exit `visual mode`, losing the current selection.

## More info
In practice this mean we can't perform heavy operations over the selection, such as:

* `vim.lsp.buf.format()`

Some fast operations such as yank/paste/delete applied over visual selection currently work as expected because they are performed before nvmenu exit visual mode.

**Comment by siduck** [comment]
>  yank/paste/delete

i wasnt able to make that work, because after the menu opens, old visual selection got cleared

**Comment by siduck** [comment]
![image](https://github.com/user-attachments/assets/672deb6c-34b7-4e6f-8870-37467f8ce16c)

@Zeioth  use gv to select last visual selection

![image](https://github.com/user-attachments/assets/7a3eab85-6f62-4697-99ab-c30e74205173)
