### ISSUE TITLE
Feature request: some APIs

### ISSUE THREAD

**Issue by epheien** [NvChad/menu#6]
1. check menu is open
2. close menu

**Comment by siduck** [comment]
you're supposed to press enter or press q/esc to close the window.

As for mouse=true, you can just click outside the menu and it'll close

**Comment by epheien** [comment]
> you're supposed to press enter or press q/esc to close the window.
> 
> As for mouse=true, you can just click outside the menu and it'll close

The problem is that if I press the mouse twice, the menu will pop up twice.
```lua
      local callback = function(mouse)
        return function()
          local options = vim.bo.ft == "NvimTree" and "nvimtree" or "mydef"
          require("menu").open(options, { mouse = mouse, border = false })
        end
      end
      vim.keymap.set("n", "<RightRelease>", callback(true), {})
      vim.keymap.set("n", "Z", callback(false), { nowait = true })
```

<img width="742" alt="Xnip2024-10-09_12-00-14" src="https://github.com/user-attachments/assets/88e53e2c-3019-4238-a77d-8c43cc32cf4e">

**Comment by siduck** [comment]
right click twice you mean?

**Comment by epheien** [comment]
> right click twice you mean?

Yes.
The expectation is to close the menu and then reopen it.

So I need to know if menu is open then close it, finally open it.

**Comment by siduck** [comment]
```lua
local menu_opened =  #require("menu.state").bufids > 0
```

**Comment by epheien** [comment]
> ```lua
> local menu_opened =  #require("menu.state").bufids > 0
> ```

It works.

And is there still an interface to manualy close the menu?

**Comment by siduck** [comment]
you need to focus on the menu and press q

to do this programmatically, use nvim_buf_call and get any  bufid from the bufids
and callback should be this :
`vim.api.nvim_feedkeys("q", "x", false)`

**Comment by siduck** [comment]
@epheien the issue should be fixed now, it wont allow more than 1 menu instance
