### ISSUE TITLE
Menu disabling my NVDash from loading on startup + can't open in nvimtree

### ISSUE THREAD

**Issue by micahkepe** [NvChad/menu#7]
Hello, I have set in my `chadrc.lua` file my nvdash to load on startup, but when I installed the plugin with the mappings as per the README instructions, now my nvdash is not loading on startup. 

Additionally, I have been unable to open the options menu in the NvimTree explorer with either right click or the <C-t> mapping.

Any help is appreciated!

**Comment by siduck** [comment]
nvdash isnt in M.ui table anymore, it has its own table M.nvdash.

**Comment by HRKings** [comment]
Sorry to commend on a closed thread, but I found myself with the same problem, using `:lua print(vim.bo.filetype)` with nvdash set to open on startup says that the filetype of nvimtree is NvDash, I need to close all buffers and reopen before I can use the menu with NvimTree

nvdash is already on its own table on my configs

**Comment by siduck** [comment]
show video of the issue's behavior @HRKings

**Comment by HRKings** [comment]
@siduck sure, here it is:

https://github.com/user-attachments/assets/f1415005-2ca3-421b-9d71-b25c3c3986f9

and the filetype before and after reopening all buffers:


https://github.com/user-attachments/assets/94950b5f-6121-457b-84fb-63583b2ebbfe

**Comment by siduck** [comment]
i get the issue now, will push the fix tomorrow

**Comment by siduck** [comment]
check now @HRKings

**Comment by HRKings** [comment]
@siduck it works now, thanks!
