### ISSUE TITLE
Issue when using a split window

### ISSUE THREAD

**Issue by TheLazyLemur** [NvChad/menu#8]
I just want to start by saying, I really am enjoying this plugin. Its beautiful.

However I am having an issue. If I have a split open, the cursor doesnt always snap back to my last split, it will snap back to a different split altogether.

I have attached a video with the behaviour in question.

https://github.com/user-attachments/assets/977aaa86-6f8a-4e54-979e-15426e7ff838

**Comment by siduck** [comment]
will debug today

**Comment by TheLazyLemur** [comment]
Was doing some debugging and found the issue to occur only when opening a sub menu
